<?xml version="1.0" encoding="utf-8"?><Database Name="iCatalog" Class="iCatalogdbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=SEBA-PC;Initial Catalog=iCatalog;Integrated Security=True" SettingsObjectName="iCatalogData.Properties.Settings" SettingsPropertyName="iCatalogConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CatalogDetail" Member="CatalogDetails">
    <Type Name="CatalogDetail">
      <Column Name="IdCatalogDetail" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdCatalogHeader" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdProduct" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PageOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="CatalogHeader_CatalogDetail" Member="CatalogHeader" ThisKey="IdCatalogHeader" OtherKey="IdCatalogHeader" Type="CatalogHeader" IsForeignKey="true" />
      <Association Name="Product_CatalogDetail" Member="Product" ThisKey="IdProduct" OtherKey="IdProduct" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CatalogHeader" Member="CatalogHeaders">
    <Type Name="CatalogHeader">
      <Column Name="IdCatalogHeader" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CatalogCode" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="CatalogDescription" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="DateTo" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateFrom" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Pages" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdCompany" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdVisibility" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="CatalogHeader_CatalogDetail" Member="CatalogDetails" ThisKey="IdCatalogHeader" OtherKey="IdCatalogHeader" Type="CatalogDetail" />
      <Association Name="CatalogHeader_UserCatalog" Member="UserCatalogs" ThisKey="IdCatalogHeader" OtherKey="IdCatalogHeader" Type="UserCatalog" />
      <Association Name="Company_CatalogHeader" Member="Company" ThisKey="IdCompany" OtherKey="IdCompany" Type="Company" IsForeignKey="true" />
      <Association Name="Visibility_CatalogHeader" Member="Visibility" ThisKey="IdVisibility" OtherKey="IdVisibility" Type="Visibility" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CategoryOne" Member="CategoryOnes">
    <Type Name="CategoryOne">
      <Column Name="IdCategoryOne" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CategoryName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CategoryDescription" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="IdCompany" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="CategoryOne_Product" Member="Products" ThisKey="IdCategoryOne" OtherKey="IdCategoryOne" Type="Product" />
      <Association Name="Company_CategoryOne" Member="Company" ThisKey="IdCompany" OtherKey="IdCompany" Type="Company" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CategoryThree" Member="CategoryThrees">
    <Type Name="CategoryThree">
      <Column Name="IdCategoryThree" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CategoryName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CategoryDescription" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="IdCompany" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="CategoryThree_Product" Member="Products" ThisKey="IdCategoryThree" OtherKey="IdCategoryThree" Type="Product" />
      <Association Name="Company_CategoryThree" Member="Company" ThisKey="IdCompany" OtherKey="IdCompany" Type="Company" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CategoryTwo" Member="CategoryTwos">
    <Type Name="CategoryTwo">
      <Column Name="IdCategoryTwo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CategoryName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CategoryDescription" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="IdCompany" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="CategoryTwo_Product" Member="Products" ThisKey="IdCategoryTwo" OtherKey="IdCategoryTwo" Type="Product" />
      <Association Name="Company_CategoryTwo" Member="Company" ThisKey="IdCompany" OtherKey="IdCompany" Type="Company" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Cities" Member="Cities">
    <Type Name="City">
      <Column Name="IdCity" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CityName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IdCountry" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="City_Company" Member="Companies" ThisKey="IdCity" OtherKey="IdCity" Type="Company" />
      <Association Name="City_User" Member="Users" ThisKey="IdCity" OtherKey="IdCity" Type="User" />
      <Association Name="Country_City" Member="Country" ThisKey="IdCountry" OtherKey="IdCountry" Type="Country" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Companies" Member="Companies">
    <Type Name="Company">
      <Column Name="IdCompany" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CompanyName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="IdCountry" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdCity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="WebUrl" Type="System.String" DbType="NVarchar(100)" CanBeNull="false" />
      <Column Name="CompanyUserName" Type="System.String" DbType="nvarchar(50)" CanBeNull="false" />
      <Association Name="Company_CatalogHeader" Member="CatalogHeaders" ThisKey="IdCompany" OtherKey="IdCompany" Type="CatalogHeader" />
      <Association Name="Company_CategoryOne" Member="CategoryOnes" ThisKey="IdCompany" OtherKey="IdCompany" Type="CategoryOne" />
      <Association Name="Company_CategoryThree" Member="CategoryThrees" ThisKey="IdCompany" OtherKey="IdCompany" Type="CategoryThree" />
      <Association Name="Company_CategoryTwo" Member="CategoryTwos" ThisKey="IdCompany" OtherKey="IdCompany" Type="CategoryTwo" />
      <Association Name="Company_File" Member="Files" ThisKey="IdCompany" OtherKey="IdCompany" Type="File" />
      <Association Name="Company_Product" Member="Products" ThisKey="IdCompany" OtherKey="IdCompany" Type="Product" />
      <Association Name="Company_Visibility" Member="Visibilities" ThisKey="IdCompany" OtherKey="IdCompany" Type="Visibility" />
      <Association Name="City_Company" Member="City" ThisKey="IdCity" OtherKey="IdCity" Type="City" IsForeignKey="true" />
      <Association Name="Country_Company" Member="Country" ThisKey="IdCountry" OtherKey="IdCountry" Type="Country" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Countries" Member="Countries">
    <Type Name="Country">
      <Column Name="IdCountry" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CountryName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Country_City" Member="Cities" ThisKey="IdCountry" OtherKey="IdCountry" Type="City" />
      <Association Name="Country_Company" Member="Companies" ThisKey="IdCountry" OtherKey="IdCountry" Type="Company" />
      <Association Name="Country_User" Member="Users" ThisKey="IdCountry" OtherKey="IdCountry" Type="User" />
    </Type>
  </Table>
  <Table Name="dbo.Devices" Member="Devices">
    <Type Name="Device">
      <Column Name="IdDevice" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DeviceCode" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="DeviceDescription" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IdUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="User_Device" Member="User" ThisKey="IdUser" OtherKey="IdUser" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Files" Member="Files">
    <Type Name="File">
      <Column Name="IdFile" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FileName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FileDescription" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="[File]" Member="File1" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="IdCompany" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="File_ProductsFile" Member="ProductsFiles" ThisKey="IdFile" OtherKey="IdFile" Type="ProductsFile" />
      <Association Name="Company_File" Member="Company" ThisKey="IdCompany" OtherKey="IdCompany" Type="Company" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Products" Member="Products">
    <Type Name="Product">
      <Column Name="IdProduct" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ProductDescription" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="IdCategoryOne" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdCategoryTwo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdCategoryThree" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdCompany" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Product_CatalogDetail" Member="CatalogDetails" ThisKey="IdProduct" OtherKey="IdProduct" Type="CatalogDetail" />
      <Association Name="Product_ProductsFile" Member="ProductsFiles" ThisKey="IdProduct" OtherKey="IdProduct" Type="ProductsFile" />
      <Association Name="CategoryOne_Product" Member="CategoryOne" ThisKey="IdCategoryOne" OtherKey="IdCategoryOne" Type="CategoryOne" IsForeignKey="true" />
      <Association Name="CategoryThree_Product" Member="CategoryThree" ThisKey="IdCategoryThree" OtherKey="IdCategoryThree" Type="CategoryThree" IsForeignKey="true" />
      <Association Name="CategoryTwo_Product" Member="CategoryTwo" ThisKey="IdCategoryTwo" OtherKey="IdCategoryTwo" Type="CategoryTwo" IsForeignKey="true" />
      <Association Name="Company_Product" Member="Company" ThisKey="IdCompany" OtherKey="IdCompany" Type="Company" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProductsFiles" Member="ProductsFiles">
    <Type Name="ProductsFile">
      <Column Name="IdProductFile" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdProduct" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdFile" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="File_ProductsFile" Member="File" ThisKey="IdFile" OtherKey="IdFile" Type="File" IsForeignKey="true" />
      <Association Name="Product_ProductsFile" Member="Product" ThisKey="IdProduct" OtherKey="IdProduct" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserCatalogs" Member="UserCatalogs">
    <Type Name="UserCatalog">
      <Column Name="IdUserCatalog" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdCatalogHeader" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="CatalogHeader_UserCatalog" Member="CatalogHeader" ThisKey="IdCatalogHeader" OtherKey="IdCatalogHeader" Type="CatalogHeader" IsForeignKey="true" />
      <Association Name="User_UserCatalog" Member="User" ThisKey="IdUser" OtherKey="IdUser" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="IdUser" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IsGeneralAdmin" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IdCountry" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdCity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="nvarchar(50)" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="nvarchar(50)" CanBeNull="false" />
      <Association Name="User_Device" Member="Devices" ThisKey="IdUser" OtherKey="IdUser" Type="Device" />
      <Association Name="User_UserCatalog" Member="UserCatalogs" ThisKey="IdUser" OtherKey="IdUser" Type="UserCatalog" />
      <Association Name="City_User" Member="City" ThisKey="IdCity" OtherKey="IdCity" Type="City" IsForeignKey="true" />
      <Association Name="Country_User" Member="Country" ThisKey="IdCountry" OtherKey="IdCountry" Type="Country" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Visibility" Member="Visibilities">
    <Type Name="Visibility">
      <Column Name="IdVisibility" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="VisibilityName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="VisibilityDescription" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="PercentOfVisibilityPages" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="IdCompany" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Visibility_CatalogHeader" Member="CatalogHeaders" ThisKey="IdVisibility" OtherKey="IdVisibility" Type="CatalogHeader" />
      <Association Name="Company_Visibility" Member="Company" ThisKey="IdCompany" OtherKey="IdCompany" Type="Company" IsForeignKey="true" />
    </Type>
  </Table>
</Database>